server:  port: 9192

spring:  data:    mongodb:      database: Customer
      host: localhost
      port: 27017  application:    name: CUSTOMER-SERVICE  autoconfigure:    exclude:    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
   
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka
  instance:
     hostname: localhost
      
